### ISSUE TITLE
Frontend breaks a lot

### ISSUE THREAD

**Issue by DaanDD** [sumocoders/Framework#67]
Frontend development on the new framework is pretty buggy at the moment. Below are some errors I frequently get while developing:

![screen shot 2015-06-22 at 10 56 24](https://cloud.githubusercontent.com/assets/1300724/8331474/e687c68c-1a88-11e5-9a87-13cd1e75f39c.png)
Usually app/console cache:clear or app/console assetic:dump works when I get this error.

![screen shot 2015-06-22 at 11 02 49](https://cloud.githubusercontent.com/assets/1300724/8331501/08f87a86-1a89-11e5-8d11-139d816ec770.png)
Sometimes I get no CSS at all, and sometimes I get redirected to the login page when I want to access the CSS code. Running grunt build again usually works in this case.

![screen shot 2015-06-22 at 13 55 37](https://cloud.githubusercontent.com/assets/1300724/8331533/38c81046-1a89-11e5-862a-1770ee5ab3bc.png)
Some random cache error once again. Sometimes it goes away after refreshing a few times, if that doesn't work I have to run grunt build again.

![screen shot 2015-06-22 at 13 55 58](https://cloud.githubusercontent.com/assets/1300724/8331580/6fb7fb98-1a89-11e5-8c18-819f1f527678.png)
![screen shot 2015-06-24 at 15 56 09](https://cloud.githubusercontent.com/assets/1300724/8331616/95c42834-1a89-11e5-8b27-0dd5830ecdea.png)
![screen shot 2015-06-24 at 15 57 36](https://cloud.githubusercontent.com/assets/1300724/8331655/c577150a-1a89-11e5-990d-8df1ec9644c9.png)

Sometimes I get these kinds of errors while running grunt build. When I run grunt build again it usually goes away.

Writing frontend code like this is pretty frustrating because I waste a lot of time running grunt build for the millionth time or clearing the cache once more.

**Comment by tijsverkoyen** [comment]
There are several issues:
* vagrant: the changes aren't always available directly on the vagrant box due to latency issues. This is something we can't fix.
* watch tasks: the watch-task has to do a lot of things and in some cases it triggers multiple processes that touches the same file as another process, the only thing that will resolve this is to simply a lot of the grunt-tasks
* grunt + assetic: we use assetic to manage our assets, the benefit is that in development we have separate files where in production we have a single combined file. But the combination of grunt + ascetic is a disaster, once again simplifying the grunt-code would be possible solutions

So there is no real solution.

Could you try to run `rm -rf app/cache/dev` instead of `clean:removeSymfonyCache`.

**Comment by DaanDD** [comment]
The biggest problem seems to be the combination of Grunt + Assetic. Frontend development for Fork CMS, which also happens through Vagrant, doesn't give any problems.

Wouldn't it be possible to throw out Assetic completely? Grunt can also concatenate assets through [grunt-usemin](https://github.com/yeoman/grunt-usemin). Even more modern is [Webpack](http://webpack.github.io/), which lets you simply require modules inside Javascript. I use it for my personal projects and it's awesome.

**Comment by WouterSioen** [comment]
Something like this then? http://php-symfony2.blogspot.be/2014/11/symfony-without-assetic.html

I think it would be nice to drop assetic, since it's in my opinion the most frustrating part of using Symfony.
The biggest problem I see though, is external bundles providing their own assets (and assuming we use assetic).

**Comment by tijsverkoyen** [comment]
As we integrated gulp, this should be faster. I will create a separate issue to drop ascetic
